GenFit/GenFit

CMakeLists.txt
test/unitTests/main.cc

First, make sure that the include paths are in correct order and genfit includes are found before anything else.
Secondly, fix a c++11 problem with gcc5.3: isnan is no longer a macro but a function in std namespace

Fix two minor issues with compilation

---

test/unitTests/main.cc

As pointed out in #12 the previous fix for a compilation on gcc 5.3 does not work with gcc 4.9 and c++11.
This pull request basically reverts #10 and adds std:: to the isnan call. Testet on Ubuntu 14.04 and 16.04 with gcc 4.8, 4.9, 5.2 each with ROOT 6 (for c++11) and ROOT 5.34 (for c++03) so hopefully this should work everywhere.

Next try with isnan: let's see if it works in C++03 with std::

---

fitters/src/KalmanFitterRefTrack.cc

...which prevented to use genfit with more than one hypothesis. This was never seen before because the genfitter module only used one hypothesis at a time - wheeras the new RecoTrack can use more hypotheses.

Fixed a quite hard-to-find bug... 

---

fitters/include/DAF.h

The Constructors in DAF.cc use a different parameter naming as in the header file DAF.h. deltaPval and deltaWeight is swapped. This is very error prone if users want to pass custom values for deltaPval and deltaWeight to the constructor, as actually the other value will be set.
This PR fixes the order and will not affect working code, as the ordering is kept the same in the actual implementation, merely the names are changed in the .h file.

changed order of parameters in DAF Constructor

---

fitters/src/DAF.cc

The abs() method was used for floating point input values, which resulted in the output of abs being truncated to 0.0 for all values < 1.0. This in turn renders the early termination value deltaP useless, because the comparison in the fixed line is always smaller than deltaP's default of 0.001. Furthermore, we observed that different compiler versions/libraries interpret abs() differently. While GCC5 (with the Belle II software stack) used the integer version ::abs(), GCC6 stared to use the floating point version std::abs()
This PR fixes this ambiguity by using the fabs() method which is always properly interpreted as the floating point abs. On the Belle II track fitting side, the implications of the changed DAF behaviour are understood and will be applied with a custom deltaP setting: …

Changed to use floating-point version of fabs in DAF

---

.travis.yml

I checked the environment of TravisCI and it turns out that the ROOT6 binary provided at https://root.cern.ch/content/release-60608 is compatible with it. This allows us to run the integration build against the new ROOT version, which is also used at e.g. Belle II.

TravisCI with ROOT6

---

core/include/TrackPoint.h
core/src/TrackPoint.cc

During basf2 development, a bug in the TrackPoint::Streamer was found, which leads to a crash (see https://agira.desy.de/browse/BII-1836 if you have access).
In short: The Streamer silently assumes, that there is a continuous list of track representations (with continuous integer-valued ids from 0 to n-1) in each track point fit status. This may not be true for multiple hypothesis fitting, because some of the hypothesis may fail.

Fixing the track point streamer

---

CMakeLists.txt

Remove c++03 as an option from the CMakeLists and drop the support. This also changes the version number to 2.1.0 to mark the break of backward compatibility.

Drop c++03

---

.travis.yml
CMakeLists.txt
core/src/TrackPoint.cc
test/makeGeom.C

GenFit master was broken for a while with ROOT 5 since C++11 features were used, but C++11 was only enforced as a standard if compiled against ROOT 6. 
This two commit series adds: 
- Travis testing for both ROOT 5 and ROOT 6. ROOT 6 version is bumped. 
- Always require C++11, GenFit itself needs this by now. 
- Add a missing include (which is exposed via `TBuffer.h` in ROOT 6, but not in ROOT 5). 
- Use `NULL` instead of `nullptr` in the asserts in the testing-macro for ROOT 5 compatibility. No other adaptions were needed. 
This fixes compilation with ROOT 5 and ensures it stays tested.

Travis: add ROOT 5 testing and fix that, bump ROOT 6. Enforce C++11. 

---

core/include/Track.h
core/src/AbsFitter.cc
core/src/Track.cc
eventDisplay/src/EventDisplay.cc
test/fitterTests/main.cc
test/measurementFactoryExample/main.cc
test/minimalFittingExample/main.cc
test/minimalFittingExample/main2.cc
test/streamerTest/main.cc

Let checkConsistency throw instead of returning a boolean to allow exception handling instead of assertions.

Issue #38 Exceptions instead of Assertions

---

.travis.yml
test/streamerTest/main.cc

Again, mainly to handle that Travis does not like large logs and to make the output more readable.

Less verbose streamer test

---

core/include/ThinScatterer.h

This was forgotten when the MaterialProperties class was simplified to the Material struct.

Increase ThinScatterer ClassDef because the member changed.

---

fitters/include/DAF.h
fitters/include/KalmanFitterInfo.h
fitters/src/KalmanFitterInfo.cc

Getter functions should (usually) not change the object and should therefore be constant
Needed to do stuff like this:
```C++
std::vector<const genfit::KalmanFitterInfo*> kalmanFitterInfos;
...
kalmanFitterInfos[i]->getSmoothedChi2();
```
This won't compile without the member function being marked `const`

Add missing const to Getter functions

---

core/include/Exception.h
core/src/Exception.cc

Original by M. Ritter for basf2.

Dynamic throw specifications are deprecated and removed in C++17 

---

core/include/Track.h
core/src/Track.cc

This is different to just deleting the rep, because the rep pointers are not invalidated.
Useful if you want to refit a given hypothesis from scratch (e.g. because some external inputs have changed).

Added a function to reset the fit result for a given rep

---

GBL/include/GFGbl.h
GBL/include/GblFitStatus.h
GBL/include/GblFitter.h
GBL/include/GblFitterInfo.h
core/include/MeasuredStateOnPlane.h
core/include/MeasurementOnPlane.h
fitters/include/DAF.h
fitters/include/KalmanFitStatus.h
fitters/include/KalmanFitter.h
fitters/include/KalmanFitterInfo.h
fitters/include/KalmanFitterRefTrack.h
fitters/include/ReferenceStateOnPlane.h
measurements/include/FullMeasurement.h
measurements/include/HMatrixU.h
measurements/include/HMatrixUV.h
measurements/include/HMatrixV.h
measurements/include/PlanarMeasurement.h
measurements/include/SpacepointMeasurement.h
measurements/include/WireMeasurement.h
measurements/include/WireMeasurementNew.h
measurements/include/WirePointMeasurement.h
measurements/include/WireTrackCandHit.h
trackReps/include/RKTrackRep.h
trackReps/include/TGeoMaterialInterface.h

After running cppcheck 1.85 and clang we got a lot of warnings for
missing `override` keywords. This patch adds override in all places
either cppcheck of clang complained about.
Also, if appropriate `ClassDef` has been replaced with `ClassDefOverride`: if a parent class has already a `ClassDef` then this will add all members with an override keyword.

Use override Keyword

---

GBL/include/GblTrackSegmentController.h
GBL/src/GblFitter.cc
GBL/src/GblTrajectory.cc

Two important changes needed for Belle II software (basf2):
- bugfix in GBL composed trajectories used for alignment with two-body-decays (ad-hoc bugfix, without full GBL update (to EIGEN version) - needs more work)
- pass additional parameter to be able to turn off multiple scattering in Central Drift Chamber (CDC) of Belle II if only small amount of material (gas) is found between measurement - too many scatterers were causing problems with positive-definitiveness of matrices due to rounding errors

Fix gbl bug extend controller

---

GBL/src/GblFitterInfo.cc

The auxInfo (stores info about track direction) was not copied from reference (default was always used).
We keep it internally now (in the mutable / cached members fittedStateBwd_, fittedStateFwd_) and pass it over whenever we create a new MeasuredStateOnPlane.

Use auxInfo from reference

---

CMakeLists.txt
trackReps/include/MaterialEffects.h
trackReps/include/MonopoleConstants.h
trackReps/include/MplTrackRep.h
trackReps/include/RKTrackRep.h
trackReps/src/MaterialEffects.cc
trackReps/src/MplTrackRep.cc
trackReps/src/trackRepsLinkDef.h

Hello,
I have been working on the possibility of using genfit to fit tracks of magnetically charged particles, i.e. magnetic monopoles of low magnetic charge. Essentially it is the same as fitting normal tracks of electrically charged particles flying in an _electrric field_, but there are extra quirks so I think it makes sense to add this magnetic fitter explicitly.
There are two main things added:
- Monopole track representation inherited from RKTrackRep, but based on a different equation of motion.
- Material effects tweaking - use effective charge for monopole ionisation.

Track representation for magnetic monopoles

---

trackReps/src/MaterialEffects.cc
trackReps/src/MplTrackRep.cc

Follow-up after previous PR.
For some reason in 2 out of 3 places in material effects, I have incorrectly set effective charge as g*sqrt(beta).
And in the monopole propagation in some places g was hardcoded as 1.0.

Monopole bugfix

---

cmake/settings.cmake

This removes the restriction on the installation prefix. I don't see why this should ever be here. 
Also, in-source-installs should be considered evil.

Fix installation prefix convetion.

---

core/include/StateOnPlane.h
trackReps/include/RKTools.h
trackReps/include/StepLimits.h

Added some default constructors to prevent deprecation warnings when compiling with newer compiler versions (e.g. when compiling with basf2)

Prevent deprecation warnings when compiling with newer versions

---

.travis.yml

Updated the precompiled root versions and according to this the compiler version in the travis config. Travis is now not longer using ubuntu 14, but 16 (aka Xenial) what made the build fail.

Fix master build

---

eventDisplay/src/EventDisplay.cc

While compiling basf2 with clang, I noticed the followig warning:
`warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]`
(for checking the warning, you can inspect the following log of a bamboo build for basf2: https://bamboo.desy.de/download/B2-BASF29007-JOB1/build_logs/B2-BASF29007-JOB1-6.log or, even better: https://travis-ci.org/github/GenFit/GenFit/jobs/770674354#L544)
A simple evaluation of the argument of 'typeid' outside it not only fixes the warning, but it also makes the code a bit more readable and clear.

Fix a clang warning

---

.travis.yml
CMakeLists.txt
cmake/genfit.cmake

Make building the tests explicitly optional by using `CTest` facilities, instead of having it implicitly depend on the presence of `GTest`.
This will add a new option `BUILD_TESTING` to the cmake configuration, which defaults to `ON`. If this option is set, then finding `GTest` is mandatory. It also enables integration with `ctest`, so that calling `ctest` after building will automatically run all tests (the original `bin/gtests` is still available and unchanged).

Make building tests explicitly optional

---

gtest/TestRKTrackRep.cpp
test/streamerTest/main.cc
trackReps/include/RKTools.h

I am thinking to move basf2 from C++17 to C++20. As expected, I found few compiler errors, and one is from GenFit, so let me fix it.
I tested that GenFit compiles with both C++17 and C++20 using gcc/g++ and clang/clang++.
(In the meanwhile, I also fixed a couple of compiler warnings.)

Let GenFit compile when C++20 is enabled

---

core/src/Track.cc

This fix the "=" operator, before it was setting the track only on the last TrackPoint, and not on all of them.

Fix of the assignment operator

---

.github/workflows/cmake.yml

Since the travis CI stopped working its a good time to transfer the CI to github actions

Moving from travis.ci to github-actions

---

fitters/src/DAF.cc

Fix compiler warning about private members initialized in the wrong order
(I may also fix the other warnings since I am here...)

Fix compiler warning

---

fitters/include/DAF.h
fitters/src/DAF.cc

In the newest DAF constructor (the one touched by this PR), the maximum number of iterations of the Kalman was set to the same number of maximum iterations of the DAF. This badly affects the execution time of the DAF by largely increasing it. This PR sets the maximum number of iterations of the Kalman to 1 as in the other constructors.
I also modified the constructor by passing the `std::tuple` by reference and I added the `<tuple>` header.

Set to 1 the maximum number of iterations of the Kalman in the newest DAF constructor

---

fitters/include/DAF.h
fitters/src/DAF.cc

In DAF.cc there is a hard-coded selection on the minimum pValue > 1e-10 which is hardcoded, in line 154:
status->getBackwardPVal() > 1e-10 && lastPval > 1e-10 && fabs(lastPval - status->getBackwardPVal()) < this->deltaPval_) {
We (Belle II) would like to have it as data member, so that this is possible to change this value.
It solves #130

Converting the minimum allowed Pvalue into a data member

---

fitters/include/DAF.h

Before the default minPval was set to 1E-10,  but this could be too selective. We move to a conservative value of 0.

Set defaut minPval to 0

---

CMakeLists.txt

This avoids that CMake also goes looking for a C compiler and speeds up the cmake stage slightly. More importantly it makes genfit build with spack, where it is marked as a c++ project only at the moment.
See, https://github.com/spack/spack/pull/49993 for the fix from the other side on spack.

Specify genfit as a c++ project

---

.github/workflows/cmake.yml

- Update runner from Ubuntu 20.04 to Ubuntu 22.04
- Update ROOT 6.24 and 6.30 used for testing to their latest patch versions
- Add ROOT 6.34 to the pipeline
Tagging @TadeasB .

Update GitHub actions

---

fitters/src/DAF.cc

As largely discussed in Belle II, the requirement `lastPval >= minPval_` correctly mimics the older behavior of DAF.
@TadeasB

Require lastPval >= minPval_ in order to mimic older behaviour of DAF
